/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "../encoder_case.v:1" *)
module encoder_case(Code, Data);
  (* src = "../encoder_case.v:6" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  (* src = "../encoder_case.v:3" *)
  output [2:0] Code;
  (* src = "../encoder_case.v:2" *)
  input [7:0] Data;
  INVX1 _29_ (
    .A(Data[4]),
    .Y(_02_)
  );
  OR2X2 _30_ (
    .A(Data[0]),
    .B(Data[1]),
    .Y(_03_)
  );
  OR2X2 _31_ (
    .A(Data[2]),
    .B(Data[3]),
    .Y(_04_)
  );
  OR2X2 _32_ (
    .A(Data[6]),
    .B(Data[7]),
    .Y(_05_)
  );
  NOR3X1 _33_ (
    .A(_03_),
    .B(_04_),
    .C(_05_),
    .Y(_06_)
  );
  NAND3X1 _34_ (
    .A(_02_),
    .B(Data[5]),
    .C(_06_),
    .Y(_07_)
  );
  INVX1 _35_ (
    .A(Data[6]),
    .Y(_08_)
  );
  OR2X2 _36_ (
    .A(Data[4]),
    .B(Data[5]),
    .Y(_09_)
  );
  NOR3X1 _37_ (
    .A(_03_),
    .B(_04_),
    .C(_09_),
    .Y(_10_)
  );
  NAND3X1 _38_ (
    .A(_08_),
    .B(Data[7]),
    .C(_10_),
    .Y(_11_)
  );
  INVX1 _39_ (
    .A(Data[3]),
    .Y(_12_)
  );
  NOR3X1 _40_ (
    .A(Data[2]),
    .B(_12_),
    .C(_03_),
    .Y(_13_)
  );
  INVX1 _41_ (
    .A(Data[1]),
    .Y(_14_)
  );
  NOR3X1 _42_ (
    .A(Data[0]),
    .B(_14_),
    .C(_04_),
    .Y(_15_)
  );
  NOR2X1 _43_ (
    .A(_05_),
    .B(_09_),
    .Y(_16_)
  );
  OAI21X1 _44_ (
    .A(_13_),
    .B(_15_),
    .C(_16_),
    .Y(_17_)
  );
  NAND3X1 _45_ (
    .A(_07_),
    .B(_11_),
    .C(_17_),
    .Y(_00_[0])
  );
  NAND2X1 _46_ (
    .A(Data[6]),
    .B(Data[7]),
    .Y(_18_)
  );
  NAND3X1 _47_ (
    .A(_05_),
    .B(_10_),
    .C(_18_),
    .Y(_19_)
  );
  NAND2X1 _48_ (
    .A(Data[2]),
    .B(Data[3]),
    .Y(_20_)
  );
  NOR2X1 _49_ (
    .A(Data[2]),
    .B(Data[3]),
    .Y(_21_)
  );
  NOR2X1 _50_ (
    .A(_03_),
    .B(_21_),
    .Y(_22_)
  );
  NAND3X1 _51_ (
    .A(_16_),
    .B(_20_),
    .C(_22_),
    .Y(_23_)
  );
  NAND2X1 _52_ (
    .A(_19_),
    .B(_23_),
    .Y(_00_[1])
  );
  XOR2X1 _53_ (
    .A(Data[4]),
    .B(Data[5]),
    .Y(_24_)
  );
  NAND2X1 _54_ (
    .A(_06_),
    .B(_24_),
    .Y(_25_)
  );
  NAND2X1 _55_ (
    .A(_19_),
    .B(_25_),
    .Y(_00_[2])
  );
  XNOR2X1 _56_ (
    .A(Data[0]),
    .B(Data[1]),
    .Y(_26_)
  );
  NOR2X1 _57_ (
    .A(_04_),
    .B(_26_),
    .Y(_27_)
  );
  AOI22X1 _58_ (
    .A(_06_),
    .B(_24_),
    .C(_27_),
    .D(_16_),
    .Y(_28_)
  );
  NAND3X1 _59_ (
    .A(_19_),
    .B(_23_),
    .C(_28_),
    .Y(_01_)
  );
  (* src = "../encoder_case.v:6" *)
  \$_DLATCH_P_  _60_ (
    .D(_00_[0]),
    .E(_01_),
    .Q(Code[0])
  );
  (* src = "../encoder_case.v:6" *)
  \$_DLATCH_P_  _61_ (
    .D(_00_[1]),
    .E(_01_),
    .Q(Code[1])
  );
  (* src = "../encoder_case.v:6" *)
  \$_DLATCH_P_  _62_ (
    .D(_00_[2]),
    .E(_01_),
    .Q(Code[2])
  );
endmodule
