/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "../and_gate.v:1" *)
module and_gate(in1, in2, out);
  (* src = "../and_gate.v:2" *)
  input in1;
  (* src = "../and_gate.v:2" *)
  input in2;
  (* src = "../and_gate.v:3" *)
  output out;
  AND2X1 _0_ (
    .A(in1),
    .B(in2),
    .Y(out)
  );
endmodule
