/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "../ALU.v:94" *)
module ALU(A, B, S0, S1, S2, Cin, G, Cout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  (* src = "../ALU.v:95" *)
  input [3:0] A;
  (* src = "../ALU.v:95" *)
  input [3:0] B;
  (* src = "../ALU.v:97" *)
  input Cin;
  (* src = "../ALU.v:99" *)
  output Cout;
  (* src = "../ALU.v:98" *)
  output [3:0] G;
  (* src = "../ALU.v:102|../ALU.v:45" *)
  wire [3:0] \M0.A ;
  (* src = "../ALU.v:102|../ALU.v:45" *)
  wire [3:0] \M0.B ;
  (* src = "../ALU.v:102|../ALU.v:60|../ALU.v:15|../ALU.v:2" *)
  wire \M0.M1.M1.a ;
  (* src = "../ALU.v:102|../ALU.v:60|../ALU.v:16|../ALU.v:2" *)
  wire \M0.M1.M2.a ;
  (* src = "../ALU.v:102|../ALU.v:60|../ALU.v:11" *)
  wire \M0.M1.a ;
  (* src = "../ALU.v:102|../ALU.v:60|../ALU.v:11" *)
  wire \M0.M1.c_in ;
  (* src = "../ALU.v:102|../ALU.v:61|../ALU.v:15|../ALU.v:2" *)
  wire \M0.M2.M1.a ;
  (* src = "../ALU.v:102|../ALU.v:61|../ALU.v:11" *)
  wire \M0.M2.a ;
  (* src = "../ALU.v:102|../ALU.v:62|../ALU.v:15|../ALU.v:2" *)
  wire \M0.M3.M1.a ;
  (* src = "../ALU.v:102|../ALU.v:62|../ALU.v:11" *)
  wire \M0.M3.a ;
  (* src = "../ALU.v:102|../ALU.v:63|../ALU.v:15|../ALU.v:2" *)
  wire \M0.M4.M1.a ;
  (* src = "../ALU.v:102|../ALU.v:63|../ALU.v:11" *)
  wire \M0.M4.a ;
  (* src = "../ALU.v:102|../ALU.v:63|../ALU.v:12" *)
  wire \M0.M4.c_out ;
  (* src = "../ALU.v:102|../ALU.v:55|../ALU.v:34" *)
  wire \M0.N1.I1 ;
  (* src = "../ALU.v:102|../ALU.v:55|../ALU.v:33" *)
  wire \M0.N1.S0 ;
  (* src = "../ALU.v:102|../ALU.v:55|../ALU.v:33" *)
  wire \M0.N1.S1 ;
  (* src = "../ALU.v:102|../ALU.v:56|../ALU.v:34" *)
  wire \M0.N2.I1 ;
  (* src = "../ALU.v:102|../ALU.v:56|../ALU.v:33" *)
  wire \M0.N2.S0 ;
  (* src = "../ALU.v:102|../ALU.v:56|../ALU.v:33" *)
  wire \M0.N2.S1 ;
  (* src = "../ALU.v:102|../ALU.v:57|../ALU.v:34" *)
  wire \M0.N3.I1 ;
  (* src = "../ALU.v:102|../ALU.v:57|../ALU.v:33" *)
  wire \M0.N3.S0 ;
  (* src = "../ALU.v:102|../ALU.v:57|../ALU.v:33" *)
  wire \M0.N3.S1 ;
  (* src = "../ALU.v:102|../ALU.v:58|../ALU.v:34" *)
  wire \M0.N4.I1 ;
  (* src = "../ALU.v:102|../ALU.v:58|../ALU.v:33" *)
  wire \M0.N4.S0 ;
  (* src = "../ALU.v:102|../ALU.v:58|../ALU.v:33" *)
  wire \M0.N4.S1 ;
  (* src = "../ALU.v:102|../ALU.v:43" *)
  wire \M0.S0 ;
  (* src = "../ALU.v:102|../ALU.v:43" *)
  wire \M0.S1 ;
  (* src = "../ALU.v:102|../ALU.v:44" *)
  wire \M0.c_in ;
  (* src = "../ALU.v:102|../ALU.v:46" *)
  wire \M0.c_out ;
  (* src = "../ALU.v:103|../ALU.v:84" *)
  wire [3:0] \M1.A ;
  (* src = "../ALU.v:103|../ALU.v:84" *)
  wire [3:0] \M1.B ;
  (* src = "../ALU.v:103|../ALU.v:88|../ALU.v:68" *)
  wire \M1.M0.A ;
  (* src = "../ALU.v:103|../ALU.v:88|../ALU.v:68" *)
  wire \M1.M0.B ;
  (* src = "../ALU.v:103|../ALU.v:88|../ALU.v:69" *)
  wire \M1.M0.S0 ;
  (* src = "../ALU.v:103|../ALU.v:88|../ALU.v:69" *)
  wire \M1.M0.S1 ;
  (* src = "../ALU.v:103|../ALU.v:89|../ALU.v:68" *)
  wire \M1.M1.A ;
  (* src = "../ALU.v:103|../ALU.v:89|../ALU.v:68" *)
  wire \M1.M1.B ;
  (* src = "../ALU.v:103|../ALU.v:89|../ALU.v:69" *)
  wire \M1.M1.S0 ;
  (* src = "../ALU.v:103|../ALU.v:89|../ALU.v:69" *)
  wire \M1.M1.S1 ;
  (* src = "../ALU.v:103|../ALU.v:90|../ALU.v:68" *)
  wire \M1.M2.A ;
  (* src = "../ALU.v:103|../ALU.v:90|../ALU.v:68" *)
  wire \M1.M2.B ;
  (* src = "../ALU.v:103|../ALU.v:90|../ALU.v:69" *)
  wire \M1.M2.S0 ;
  (* src = "../ALU.v:103|../ALU.v:90|../ALU.v:69" *)
  wire \M1.M2.S1 ;
  (* src = "../ALU.v:103|../ALU.v:91|../ALU.v:68" *)
  wire \M1.M3.A ;
  (* src = "../ALU.v:103|../ALU.v:91|../ALU.v:68" *)
  wire \M1.M3.B ;
  (* src = "../ALU.v:103|../ALU.v:91|../ALU.v:69" *)
  wire \M1.M3.S0 ;
  (* src = "../ALU.v:103|../ALU.v:91|../ALU.v:69" *)
  wire \M1.M3.S1 ;
  (* src = "../ALU.v:103|../ALU.v:85" *)
  wire \M1.S0 ;
  (* src = "../ALU.v:103|../ALU.v:85" *)
  wire \M1.S1 ;
  (* src = "../ALU.v:96" *)
  input S0;
  (* src = "../ALU.v:96" *)
  input S1;
  (* src = "../ALU.v:96" *)
  input S2;
  (* src = "../ALU.v:105|../ALU.v:22" *)
  wire \u0.s ;
  (* src = "../ALU.v:105|../ALU.v:23" *)
  wire \u0.y ;
  (* src = "../ALU.v:106|../ALU.v:22" *)
  wire \u1.s ;
  (* src = "../ALU.v:106|../ALU.v:23" *)
  wire \u1.y ;
  (* src = "../ALU.v:107|../ALU.v:22" *)
  wire \u2.s ;
  (* src = "../ALU.v:107|../ALU.v:23" *)
  wire \u2.y ;
  (* src = "../ALU.v:108|../ALU.v:22" *)
  wire \u3.s ;
  (* src = "../ALU.v:108|../ALU.v:23" *)
  wire \u3.y ;
  BUFX2 _066_ (
    .A(S1),
    .Y(_000_)
  );
  BUFX2 _067_ (
    .A(_000_),
    .Y(_001_)
  );
  BUFX2 _068_ (
    .A(S0),
    .Y(_002_)
  );
  AOI21X1 _069_ (
    .A(_002_),
    .B(A[0]),
    .C(B[0]),
    .Y(_003_)
  );
  INVX1 _070_ (
    .A(_003_),
    .Y(_004_)
  );
  INVX1 _071_ (
    .A(_002_),
    .Y(_005_)
  );
  INVX1 _072_ (
    .A(A[0]),
    .Y(_006_)
  );
  OAI22X1 _073_ (
    .A(_002_),
    .B(A[0]),
    .C(B[0]),
    .D(_001_),
    .Y(_007_)
  );
  OAI21X1 _074_ (
    .A(_005_),
    .B(_006_),
    .C(_007_),
    .Y(_008_)
  );
  AOI21X1 _075_ (
    .A(_001_),
    .B(_004_),
    .C(_008_),
    .Y(_009_)
  );
  NAND3X1 _076_ (
    .A(_001_),
    .B(A[0]),
    .C(_004_),
    .Y(_010_)
  );
  NAND2X1 _077_ (
    .A(S2),
    .B(_010_),
    .Y(_011_)
  );
  MUX2X1 _078_ (
    .A(S0),
    .B(_000_),
    .S(B[0]),
    .Y(_012_)
  );
  NOR2X1 _079_ (
    .A(_006_),
    .B(_012_),
    .Y(_013_)
  );
  AND2X1 _080_ (
    .A(_006_),
    .B(_012_),
    .Y(_014_)
  );
  NOR2X1 _081_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  AND2X1 _082_ (
    .A(Cin),
    .B(_015_),
    .Y(_016_)
  );
  INVX1 _083_ (
    .A(S2),
    .Y(_017_)
  );
  OAI21X1 _084_ (
    .A(Cin),
    .B(_015_),
    .C(_017_),
    .Y(_018_)
  );
  OAI22X1 _085_ (
    .A(_009_),
    .B(_011_),
    .C(_016_),
    .D(_018_),
    .Y(G[0])
  );
  INVX1 _086_ (
    .A(Cin),
    .Y(_019_)
  );
  OR2X2 _087_ (
    .A(_006_),
    .B(_012_),
    .Y(_020_)
  );
  OAI21X1 _088_ (
    .A(_019_),
    .B(_014_),
    .C(_020_),
    .Y(_021_)
  );
  INVX1 _089_ (
    .A(A[1]),
    .Y(_022_)
  );
  MUX2X1 _090_ (
    .A(_002_),
    .B(_000_),
    .S(B[1]),
    .Y(_023_)
  );
  XNOR2X1 _091_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  INVX1 _092_ (
    .A(_024_),
    .Y(_025_)
  );
  AND2X1 _093_ (
    .A(_021_),
    .B(_025_),
    .Y(_026_)
  );
  OAI21X1 _094_ (
    .A(_021_),
    .B(_025_),
    .C(_017_),
    .Y(_027_)
  );
  NOR2X1 _095_ (
    .A(_005_),
    .B(_022_),
    .Y(_028_)
  );
  OAI21X1 _096_ (
    .A(B[1]),
    .B(_028_),
    .C(_001_),
    .Y(_029_)
  );
  NAND2X1 _097_ (
    .A(_002_),
    .B(A[1]),
    .Y(_030_)
  );
  OAI22X1 _098_ (
    .A(_002_),
    .B(A[1]),
    .C(B[1]),
    .D(_001_),
    .Y(_031_)
  );
  NAND3X1 _099_ (
    .A(_030_),
    .B(_029_),
    .C(_031_),
    .Y(_032_)
  );
  AND2X1 _100_ (
    .A(S2),
    .B(_032_),
    .Y(_033_)
  );
  OAI21X1 _101_ (
    .A(_022_),
    .B(_029_),
    .C(_033_),
    .Y(_034_)
  );
  OAI21X1 _102_ (
    .A(_026_),
    .B(_027_),
    .C(_034_),
    .Y(G[1])
  );
  NOR2X1 _103_ (
    .A(_022_),
    .B(_023_),
    .Y(_035_)
  );
  AOI21X1 _104_ (
    .A(_021_),
    .B(_025_),
    .C(_035_),
    .Y(_036_)
  );
  BUFX2 _105_ (
    .A(A[2]),
    .Y(_037_)
  );
  MUX2X1 _106_ (
    .A(_002_),
    .B(_000_),
    .S(B[2]),
    .Y(_038_)
  );
  XOR2X1 _107_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  XNOR2X1 _108_ (
    .A(_036_),
    .B(_039_),
    .Y(_040_)
  );
  AOI21X1 _109_ (
    .A(_002_),
    .B(_037_),
    .C(B[2]),
    .Y(_041_)
  );
  INVX1 _110_ (
    .A(_041_),
    .Y(_042_)
  );
  NAND3X1 _111_ (
    .A(_001_),
    .B(_037_),
    .C(_042_),
    .Y(_043_)
  );
  INVX1 _112_ (
    .A(_037_),
    .Y(_044_)
  );
  OAI22X1 _113_ (
    .A(_002_),
    .B(_037_),
    .C(B[2]),
    .D(_001_),
    .Y(_045_)
  );
  OAI21X1 _114_ (
    .A(_005_),
    .B(_044_),
    .C(_045_),
    .Y(_046_)
  );
  AOI21X1 _115_ (
    .A(_001_),
    .B(_042_),
    .C(_046_),
    .Y(_047_)
  );
  NOR2X1 _116_ (
    .A(_017_),
    .B(_047_),
    .Y(_048_)
  );
  NAND2X1 _117_ (
    .A(_043_),
    .B(_048_),
    .Y(_049_)
  );
  OAI21X1 _118_ (
    .A(S2),
    .B(_040_),
    .C(_049_),
    .Y(G[2])
  );
  INVX1 _119_ (
    .A(_038_),
    .Y(_050_)
  );
  NAND2X1 _120_ (
    .A(_037_),
    .B(_050_),
    .Y(_051_)
  );
  OAI21X1 _121_ (
    .A(_036_),
    .B(_039_),
    .C(_051_),
    .Y(_052_)
  );
  NAND2X1 _122_ (
    .A(_005_),
    .B(B[3]),
    .Y(_053_)
  );
  OAI21X1 _123_ (
    .A(_000_),
    .B(B[3]),
    .C(_053_),
    .Y(_054_)
  );
  XNOR2X1 _124_ (
    .A(A[3]),
    .B(_054_),
    .Y(_055_)
  );
  XNOR2X1 _125_ (
    .A(_052_),
    .B(_055_),
    .Y(_056_)
  );
  INVX1 _126_ (
    .A(A[3]),
    .Y(_057_)
  );
  NOR2X1 _127_ (
    .A(_005_),
    .B(_057_),
    .Y(_058_)
  );
  OAI21X1 _128_ (
    .A(B[3]),
    .B(_058_),
    .C(_001_),
    .Y(_059_)
  );
  OAI22X1 _129_ (
    .A(_002_),
    .B(A[3]),
    .C(B[3]),
    .D(_001_),
    .Y(_060_)
  );
  INVX1 _130_ (
    .A(_060_),
    .Y(_061_)
  );
  OAI21X1 _131_ (
    .A(_058_),
    .B(_061_),
    .C(_059_),
    .Y(_062_)
  );
  OAI21X1 _132_ (
    .A(A[3]),
    .B(_059_),
    .C(_062_),
    .Y(_063_)
  );
  NAND2X1 _133_ (
    .A(S2),
    .B(_063_),
    .Y(_064_)
  );
  OAI21X1 _134_ (
    .A(S2),
    .B(_056_),
    .C(_064_),
    .Y(G[3])
  );
  NAND2X1 _135_ (
    .A(_052_),
    .B(_055_),
    .Y(_065_)
  );
  OAI21X1 _136_ (
    .A(_057_),
    .B(_054_),
    .C(_065_),
    .Y(Cout)
  );
  assign \M0.M2.M1.a  = A[1];
  assign \M0.M1.c_in  = Cin;
  assign \M0.M1.a  = A[0];
  assign \M0.M3.M1.a  = A[2];
  assign \M0.M3.a  = A[2];
  assign \M0.M1.M2.a  = Cin;
  assign \M0.M1.M1.a  = A[0];
  assign \M0.M2.a  = A[1];
  assign \M0.M4.M1.a  = A[3];
  assign \M0.B  = B;
  assign \M0.A  = A;
  assign \M0.M4.a  = A[3];
  assign \M0.M4.c_out  = Cout;
  assign \M0.N1.I1  = B[0];
  assign \M0.N1.S0  = S0;
  assign \M0.N1.S1  = S1;
  assign \M0.N2.I1  = B[1];
  assign \M0.N2.S0  = S0;
  assign \M0.N2.S1  = S1;
  assign \M0.N3.I1  = B[2];
  assign \M0.N3.S0  = S0;
  assign \M0.N3.S1  = S1;
  assign \M0.N4.I1  = B[3];
  assign \M0.N4.S0  = S0;
  assign \M0.N4.S1  = S1;
  assign \M0.S0  = S0;
  assign \M0.S1  = S1;
  assign \M0.c_in  = Cin;
  assign \M0.c_out  = Cout;
  assign \M1.A  = A;
  assign \M1.B  = B;
  assign \M1.M0.A  = A[0];
  assign \M1.M0.B  = B[0];
  assign \M1.M0.S0  = S0;
  assign \M1.M0.S1  = S1;
  assign \M1.M1.A  = A[1];
  assign \M1.M1.B  = B[1];
  assign \M1.M1.S0  = S0;
  assign \M1.M1.S1  = S1;
  assign \M1.M2.A  = A[2];
  assign \M1.M2.B  = B[2];
  assign \M1.M2.S0  = S0;
  assign \M1.M2.S1  = S1;
  assign \M1.M3.A  = A[3];
  assign \M1.M3.B  = B[3];
  assign \M1.M3.S0  = S0;
  assign \M1.M3.S1  = S1;
  assign \M1.S0  = S0;
  assign \M1.S1  = S1;
  assign \u0.s  = S2;
  assign \u0.y  = G[0];
  assign \u1.s  = S2;
  assign \u1.y  = G[1];
  assign \u2.s  = S2;
  assign \u2.y  = G[2];
  assign \u3.s  = S2;
  assign \u3.y  = G[3];
endmodule
